stages:
  - build
  - deploy

build:acc:
  image: 'registry.tfe.nl/frontend/docker-frontend:latest'
  stage: build
  script:
      - yarn
      - yarn build
  artifacts:
      paths:
          - ./dist
      expire_in: 1 hrs
  only:
      refs:
      		- staging
  tags:
      - docker-unrestricted

build:prd:
  image: 'registry.tfe.nl/frontend/docker-frontend:latest'
  stage: build
  script:
      - yarn
      - yarn generate
  artifacts:
      paths:
          - ./dist
			expire_in: 1 hrs
	only:
			refs:
					- master
  tags:
      - docker-unrestricted


deploy:acc:
  stage: deploy
  environment:
      name: acc
  when: manual
  image: registry.tfe.nl/continuous-integration/aws:latest
  needs:
    - job: build:acc
      artifacts: true
  tags:
      - docker-unrestricted
  only:
      refs:
          - staging
  script:
      - aws s3 sync --delete . s3://$AWS_S3_BUCKET

deploy:prd:
  stage: deploy
  environment:
    name: prd
  when: manual
  image: registry.tfe.nl/continuous-integration/aws:latest
  needs:
    - job: build:prd
      artifacts: true
  tags:
      - docker-unrestricted
  only:
      refs:
          - master
  script:
      - aws s3 sync --delete . s3://$AWS_S3_BUCKET
