stages:
  - pre
  - build
  - deploy

pre:
  stage: pre
  image: 'registry.tfe.nl/frontend/docker-frontend:latest'
  script:
    - yarn
  artifacts:
    paths:
      - ./node_modules
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - node_modules
  tags:
      - docker-unrestricted   

build:acc:
  stage: build
  image: 'registry.tfe.nl/frontend/docker-frontend:latest'
  needs:
    - job: pre
      artifacts: true
  script:
      - yarn build
  artifacts:
    expire_in: 5 min
    paths:
      - ./dist
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - node_modules
      - dist
  tags:
      - docker-unrestricted
  only:
    refs:
      - staging

build:prd:
  stage: build
  image: 'registry.tfe.nl/frontend/docker-frontend:latest'
  needs:
    - job: pre
      artifacts: true
  script:
      - yarn generate
  artifacts:
    expire_in: 5 min
    paths:
      - ./dist
  cache:
    key:
      files:
        - package.json
        - yarn.lock
    paths:
      - node_modules
      - dist
  tags:
      - docker-unrestricted
  only:
    refs:
      - master

deploy:acc:
  stage: deploy
  environment:
      name: acc
  image: registry.tfe.nl/continuous-integration/aws:latest
  needs:
    - job: build:acc
      artifacts: true
  tags:
      - docker-unrestricted
  only:
      refs:
          - staging
  script:
      - cd dist && aws s3 sync --delete . s3://$AWS_S3_BUCKET

deploy:prd:
  stage: deploy
  environment:
    name: prd
  image: registry.tfe.nl/continuous-integration/aws:latest
  needs:
    - job: build:prd
      artifacts: true
  tags:
      - docker-unrestricted
  only:
      refs:
          - master
  script:
      - cd dist && aws s3 sync --delete . s3://$AWS_S3_BUCKET
